// 题库数据 - 从 index.html 分离
var App = window.App || {};

App.QUESTION_BANK = [
// ===== 专辑 - 15题 =====
{id:"001",category:"专辑",question:"林俊杰首张专辑《乐行者》发行于哪一天？",options:[{key:"A",text:"2003年4月1日"},{key:"B",text:"2003年4月10日"},{key:"C",text:"2003年5月1日"},{key:"D",text:"2003年5月10日"}],answer:"B",explanation:"《乐行者》于2003年4月10日正式发行，这也是林俊杰的出道专辑。"},
{id:"005",category:"专辑",question:"《第二天堂》（俗称《江南》专辑）发行于哪一年？",options:[{key:"A",text:"2003年"},{key:"B",text:"2004年"},{key:"C",text:"2005年"},{key:"D",text:"2006年"}],answer:"B",explanation:"《第二天堂》于2004年6月4日发行，包含热门歌曲《江南》。"},
{id:"009",category:"专辑",question:"《编号89757》专辑的灵感来源于？",options:[{key:"A",text:"电话号码"},{key:"B",text:"机器人编号"},{key:"C",text:"房间号"},{key:"D",text:"日期"}],answer:"B",explanation:"89757是机器人编号，专辑以此概念为主题，讲述机器人爱上人类的故事。"},
{id:"013",category:"专辑",question:"林俊杰2006年发行的专辑名称是？",options:[{key:"A",text:"第二天堂"},{key:"B",text:"编号89757"},{key:"C",text:"曹操"},{key:"D",text:"西界"}],answer:"C",explanation:"《曹操》于2006年2月17日发行，是林俊杰的第四张专辑。"},
{id:"017",category:"专辑",question:"《西界》专辑发行于哪一年？",options:[{key:"A",text:"2005年"},{key:"B",text:"2006年"},{key:"C",text:"2007年"},{key:"D",text:"2008年"}],answer:"C",explanation:"《西界》于2007年6月29日发行，是林俊杰的第五张专辑。"},
{id:"021",category:"专辑",question:"《JJ陆》的英文名是？",options:[{key:"A",text:"One Shot"},{key:"B",text:"Sixology"},{key:"C",text:"Born to Dream"},{key:"D",text:"The One"}],answer:"B",explanation:"Sixology代表第六张专辑，是林俊杰的第六张专辑。"},
{id:"025",category:"专辑",question:"《100天》专辑发行于哪一年？",options:[{key:"A",text:"2008年"},{key:"B",text:"2009年"},{key:"C",text:"2010年"},{key:"D",text:"2011年"}],answer:"B",explanation:"《100天》于2009年12月18日发行。"},
{id:"029",category:"专辑",question:"《她说》专辑的发行年份是？",options:[{key:"A",text:"2009年"},{key:"B",text:"2010年"},{key:"C",text:"2011年"},{key:"D",text:"2012年"}],answer:"B",explanation:"《她说》于2010年12月8日发行。"},
{id:"033",category:"专辑",question:"《学不会》专辑发行于？",options:[{key:"A",text:"2010年"},{key:"B",text:"2011年"},{key:"C",text:"2012年"},{key:"D",text:"2013年"}],answer:"B",explanation:"《学不会》于2011年12月31日发行，是林俊杰的第九张专辑。"},
{id:"037",category:"专辑",question:"《因你而在》专辑发行于哪一年？",options:[{key:"A",text:"2012年"},{key:"B",text:"2013年"},{key:"C",text:"2014年"},{key:"D",text:"2015年"}],answer:"B",explanation:"《因你而在》于2013年3月13日发行。"},
{id:"041",category:"专辑",question:"《新地球》专辑发行于哪一年？",options:[{key:"A",text:"2013年"},{key:"B",text:"2014年"},{key:"C",text:"2015年"},{key:"D",text:"2016年"}],answer:"B",explanation:"《新地球》于2014年12月27日发行。"},
{id:"045",category:"专辑",question:"《和自己对话》专辑发行于？",options:[{key:"A",text:"2014年"},{key:"B",text:"2015年"},{key:"C",text:"2016年"},{key:"D",text:"2017年"}],answer:"B",explanation:"《和自己对话》于2015年12月25日发行，是林俊杰的首张实验专辑。"},
{id:"049",category:"专辑",question:"《伟大的渺小》专辑发行于哪一年？",options:[{key:"A",text:"2016年"},{key:"B",text:"2017年"},{key:"C",text:"2018年"},{key:"D",text:"2019年"}],answer:"B",explanation:"《伟大的渺小》于2017年12月28日发行。"},
{id:"053",category:"专辑",question:"《幸存者·如你》专辑发行于？",options:[{key:"A",text:"2017年"},{key:"B",text:"2018年"},{key:"C",text:"2019年"},{key:"D",text:"2020年"}],answer:"B",explanation:"《幸存者·如你》于2018年10月5日发行。"},
{id:"057",category:"专辑",question:"《重拾_快乐》专辑发行于？",options:[{key:"A",text:"2022年"},{key:"B",text:"2023年"},{key:"C",text:"2024年"},{key:"D",text:"2025年"}],answer:"B",explanation:"《重拾_快乐》于2023年4月21日发行，是林俊杰的最新专辑。"},
// ===== 歌曲 - 45题 =====
{id:"002",category:"歌曲",question:"《乐行者》专辑中由林俊杰本人作词的歌曲是？",options:[{key:"A",text:"就是我"},{key:"B",text:"会读书"},{key:"C",text:"不懂"},{key:"D",text:"翅膀"}],answer:"A",explanation:"《就是我》由林俊杰作词，这是他第一首完全由自己作词的作品。"},
{id:"003",category:"歌曲",question:"《第二天堂》中《江南》的作词人是谁？",options:[{key:"A",text:"林俊杰"},{key:"B",text:"张思尔"},{key:"C",text:"李瑞洵"},{key:"D",text:"方文山"}],answer:"C",explanation:"《江南》由李瑞洵作词，是林俊杰的代表作之一。"},
{id:"004",category:"歌曲",question:"《乐行者》专辑中哪首歌的作词人包含林秋离？",options:[{key:"A",text:"星空下的吻"},{key:"B",text:"会有那么一天"},{key:"C",text:"女儿家"},{key:"D",text:"让我心动的人"}],answer:"A",explanation:"《星空下的吻》由张思尔/林秋离作词。"},
{id:"006",category:"歌曲",question:"《第二天堂》专辑中《江南》的作曲人是谁？",options:[{key:"A",text:"林俊杰"},{key:"B",text:"张思尔"},{key:"C",text:"蔡政勋"},{key:"D",text:"吴庆隆"}],answer:"A",explanation:"《江南》由林俊杰作曲，是他的成名作。"},
{id:"007",category:"歌曲",question:"《第二天堂》专辑中《子弹列车》的作词人是？",options:[{key:"A",text:"林俊杰"},{key:"B",text:"方文山"},{key:"C",text:"张思尔"},{key:"D",text:"林秋离"}],answer:"B",explanation:"《子弹列车》由方文山作词，林俊杰作曲并编曲。"},
{id:"008",category:"歌曲",question:"《第二天堂》专辑中不包含以下哪首音乐？",options:[{key:"A",text:"《江南》"},{key:"B",text:"《森林浴》"},{key:"C",text:"《美人鱼》"},{key:"D",text:"《会有那么一天》"}],answer:"D",explanation:"《第二天堂》专辑包含《一开始》Demo、《起床了》、《森林浴》、《未完成》等纯音乐；《会有那么一天》是《乐行者》专辑里的歌。"},
{id:"010",category:"歌曲",question:"《编号89757》专辑中林俊杰作词的歌曲是？",options:[{key:"A",text:"一千年以前"},{key:"B",text:"莎士比亚的天份"},{key:"C",text:"木乃伊"},{key:"D",text:"一千年以后"}],answer:"B",explanation:"《莎士比亚的天份》由林俊杰作词，这是他早期展示创作才华的作品。"},
{id:"011",category:"歌曲",question:"《一千年以后》的作词人是？",options:[{key:"A",text:"林俊杰"},{key:"B",text:"李瑞洵"},{key:"C",text:"方文山"},{key:"D",text:"林秋离"}],answer:"B",explanation:"《一千年以后》由李瑞洵作词，是《一千年以前》的后续歌曲。"},
{id:"012",category:"歌曲",question:"《编号89757》专辑中《明天》的作词人是？",options:[{key:"A",text:"林俊杰"},{key:"B",text:"李瑞洵"},{key:"C",text:"张思尔"},{key:"D",text:"林秋离"}],answer:"B",explanation:"《明天》由李瑞洵作词，林俊杰作曲。"},
{id:"014",category:"歌曲",question:"《曹操》专辑中《只对你说》的作词人是？",options:[{key:"A",text:"林俊杰"},{key:"B",text:"林秋离"},{key:"C",text:"张思尔"},{key:"D",text:"林怡凤"}],answer:"A",explanation:"《只对你说》由林俊杰作词作曲，是专辑中林俊杰参与作词的歌曲。"},
{id:"015",category:"歌曲",question:"《曹操》同名主打歌的作词人是？",options:[{key:"A",text:"林俊杰"},{key:"B",text:"林秋离"},{key:"C",text:"方文山"},{key:"D",text:"张思尔"}],answer:"B",explanation:"《曹操》由林秋离作词，林俊杰作曲。"},
{id:"016",category:"歌曲",question:"《曹操》专辑中《流行教主》的作词人是？",options:[{key:"A",text:"林俊杰"},{key:"B",text:"林宇中"},{key:"C",text:"林秋离"},{key:"D",text:"张思尔"}],answer:"B",explanation:"《流行教主》由林宇中作词，林俊杰作曲。"},
{id:"018",category:"歌曲",question:"《西界》专辑中林俊杰作词的歌曲是？",options:[{key:"A",text:"杀手"},{key:"B",text:"西界"},{key:"C",text:"大男人·小女孩"},{key:"D",text:"L-O-V-E"}],answer:"C",explanation:"《大男人·小女孩》由林俊杰作词。"},
{id:"019",category:"歌曲",question:"《西界》专辑中《不流泪的机场》的作词人是？",options:[{key:"A",text:"林俊杰"},{key:"B",text:"陈嘉文"},{key:"C",text:"林秋离"},{key:"D",text:"林怡凤"}],answer:"B",explanation:"《不流泪的机场》由陈嘉文作词。"},
{id:"020",category:"歌曲",question:"《西界》专辑中《杀手》的制作人是？",options:[{key:"A",text:"许环良"},{key:"B",text:"林俊杰"},{key:"C",text:"吴剑泓"},{key:"D",text:"Kenn C"}],answer:"B",explanation:"《杀手》由林俊杰作曲并担任制作人。"},
{id:"022",category:"歌曲",question:"《不潮不用花钱》的作词人是？",options:[{key:"A",text:"林俊杰"},{key:"B",text:"林怡凤"},{key:"C",text:"方文山"},{key:"D",text:"王雅君"}],answer:"B",explanation:"《不潮不用花钱》由林怡凤作词，Rap部分由林俊杰创作。"},
{id:"023",category:"歌曲",question:"《小酒窝》是与哪位歌手合唱的？",options:[{key:"A",text:"蔡卓妍"},{key:"B",text:"邓紫棋"},{key:"C",text:"张韶涵"},{key:"D",text:"梁静茹"}],answer:"A",explanation:"《小酒窝》是林俊杰与蔡卓妍（阿Sa）合唱的歌曲。"},
{id:"024",category:"歌曲",question:"《醉赤壁》是为什么创作的主题曲？",options:[{key:"A",text:"电影"},{key:"B",text:"电视剧"},{key:"C",text:"游戏"},{key:"D",text:"广告"}],answer:"C",explanation:"《醉赤壁》是网络游戏《赤壁》的主题曲，由方文山作词。"},
{id:"026",category:"歌曲",question:"《背对背拥抱》的作词人是？",options:[{key:"A",text:"林俊杰"},{key:"B",text:"林怡凤"},{key:"C",text:"姚若龙"},{key:"D",text:"方文山"}],answer:"B",explanation:"《背对背拥抱》由林怡凤作词，是专辑中的抒情主打。"},
{id:"027",category:"歌曲",question:"《爱与希望》是为什么创作的公益歌曲？",options:[{key:"A",text:"汶川地震"},{key:"B",text:"台湾莫拉克风灾"},{key:"C",text:"菲律宾台风"},{key:"D",text:"日本地震"}],answer:"A",explanation:"《爱与希望》是2008年为汶川地震创作的公益歌曲。"},
{id:"028",category:"歌曲",question:"《转动》是为哪位艺人创作的歌曲？",options:[{key:"A",text:"成龙"},{key:"B",text:"迈克尔·杰克逊"},{key:"C",text:"结石姐"},{key:"D",text:"张惠妹"}],answer:"B",explanation:"《转动》是林俊杰为了致敬迈克尔·杰克逊而创作的歌曲，收录于《100天》专辑。"},
{id:"030",category:"歌曲",question:"《她说》的作词人是？",options:[{key:"A",text:"林俊杰"},{key:"B",text:"孙燕姿"},{key:"C",text:"林夕"},{key:"D",text:"方文山"}],answer:"B",explanation:"《她说》由孙燕姿作词，林俊杰作曲，是专辑名称的由来。"},
{id:"031",category:"歌曲",question:"《爱笑的眼睛》作词人是？",options:[{key:"A",text:"林俊杰"},{key:"B",text:"洪瑞业"},{key:"C",text:"林怡凤"},{key:"D",text:"方文山"}],answer:"B",explanation:"《爱笑的眼睛》由洪瑞业作词。"},
{id:"032",category:"歌曲",question:"《当你》是林俊杰写给谁的歌曲？",options:[{key:"A",text:"颜人中"},{key:"B",text:"孙燕姿"},{key:"C",text:"王心凌"},{key:"D",text:"张惠妹"}],answer:"C",explanation:"《当你》是林俊杰作曲，原唱是王心凌，后林俊杰于 2010 年重新编曲并翻唱，收录在专辑《她说》中。"},
{id:"034",category:"歌曲",question:"《学不会》的作词人是？",options:[{key:"A",text:"方文山"},{key:"B",text:"姚若龙"},{key:"C",text:"林夕"},{key:"D",text:"林怡凤"}],answer:"B",explanation:"《学不会》由姚若龙作词，是专辑的同名主打歌。"},
{id:"035",category:"歌曲",question:"《那些你很冒险的梦》作词人是？",options:[{key:"A",text:"林俊杰"},{key:"B",text:"王雅君"},{key:"C",text:"方文山"},{key:"D",text:"吴青峰"}],answer:"B",explanation:"《那些你很冒险的梦》由王雅君作词。"},
{id:"036",category:"歌曲",question:"《故事细腻》的作词人是？",options:[{key:"A",text:"林俊杰"},{key:"B",text:"方文山"},{key:"C",text:"林秋离"},{key:"D",text:"吴青峰"}],answer:"B",explanation:"《故事细腻》由方文山作词，林俊杰作曲。"},
{id:"038",category:"歌曲",question:"《修炼爱情》的作词人是？",options:[{key:"A",text:"林俊杰"},{key:"B",text:"易家扬"},{key:"C",text:"方文山"},{key:"D",text:"吴青峰"}],answer:"B",explanation:"《修炼爱情》由易家扬作词，是专辑热门歌曲。"},
{id:"039",category:"歌曲",question:"《黑暗骑士》是与哪位艺人合唱的？",options:[{key:"A",text:"周杰伦"},{key:"B",text:"阿信"},{key:"C",text:"周杰伦"},{key:"D",text:"怪兽"}],answer:"B",explanation:"《黑暗骑士》由林俊杰与五月天阿信合唱。"},
{id:"040",category:"歌曲",question:"《裂缝中的阳光》作词人是？",options:[{key:"A",text:"林俊杰"},{key:"B",text:"吴青峰"},{key:"C",text:"方文山"},{key:"D",text:"林怡凤"}],answer:"B",explanation:"《裂缝中的阳光》由吴青峰作词，是专辑中的抒情佳作。"},
{id:"042",category:"歌曲",question:"《可惜没如果》的作词人是？",options:[{key:"A",text:"林夕"},{key:"B",text:"方文山"},{key:"C",text:"林怡凤"},{key:"D",text:"吴青峰"}],answer:"A",explanation:"《可惜没如果》由林夕作词，是新专辑的抒情主打。"},
{id:"043",category:"歌曲",question:"《手心的蔷薇》作词人是？",options:[{key:"A",text:"方文山"},{key:"B",text:"林怡凤"},{key:"C",text:"易家扬"},{key:"D",text:"小寒"}],answer:"B",explanation:"《手心的蔷薇》由林怡凤作词，林俊杰与林怡凤合唱。"},
{id:"044",category:"歌曲",question:"《浪漫血液》作词人是？",options:[{key:"A",text:"小寒"},{key:"B",text:"易家扬"},{key:"C",text:"方文山"},{key:"D",text:"林秋离"}],answer:"B",explanation:"《浪漫血液》由易家扬作词，是专辑中的代表作之一。"},
{id:"046",category:"歌曲",question:"《不为谁而作的歌》作词人是？",options:[{key:"A",text:"林俊杰"},{key:"B",text:"林秋离"},{key:"C",text:"方文山"},{key:"D",text:"吴青峰"}],answer:"B",explanation:"《不为谁而作的歌》由林秋离作词，是专辑的主打歌。"},
{id:"047",category:"歌曲",question:"《关键词》作词人是？",options:[{key:"A",text:"林俊杰"},{key:"B",text:"林怡凤"},{key:"C",text:"林夕"},{key:"D",text:"小寒"}],answer:"B",explanation:"《关键词》由林怡凤作词，收录于《和自己对话》专辑。"},
{id:"048",category:"歌曲",question:"《弹唱》作词人是？",options:[{key:"A",text:"林俊杰"},{key:"B",text:"张思尔"},{key:"C",text:"方文山"},{key:"D",text:"吴青峰"}],answer:"B",explanation:"《弹唱》由张思尔作词，是专辑中的温馨抒情曲。"},
{id:"050",category:"歌曲",question:"《圣所》是哪场演唱会的名称？",options:[{key:"A",text:"时线演唱会"},{key:"B",text:"圣所世界巡回演唱会"},{key:"C",text:"伟大的渺小演唱会"},{key:"D",text:"JJ20演唱会"}],answer:"B",explanation:"《圣所》是林俊杰2018年开始的世界巡回演唱会名称。"},
{id:"051",category:"歌曲",question:"《黑夜问白天》作词人是？",options:[{key:"A",text:"小寒"},{key:"B",text:"易家扬"},{key:"C",text:"方文山"},{key:"D",text:"林雨果"}],answer:"B",explanation:"《黑夜问白天》由易家扬作词，是专辑中的代表作。"},
{id:"052",category:"歌曲",question:"《小瓶子》作词人是？",options:[{key:"A",text:"林俊杰"},{key:"B",text:"易家扬"},{key:"C",text:"方文山"},{key:"D",text:"小寒"}],answer:"A",explanation:"《小瓶子》由林俊杰作词，是专辑中的温馨歌曲。"},
{id:"054",category:"歌曲",question:"《交换余生》的作词人是？",options:[{key:"A",text:"林俊杰"},{key:"B",text:"易家扬"},{key:"C",text:"方文山"},{key:"D",text:"小寒"}],answer:"B",explanation:"《交换余生》由易家扬作词，是专辑的主打歌曲。"},
{id:"055",category:"歌曲",question:"《最向往的地方》作词人是？",options:[{key:"A",text:"杨彤"},{key:"B",text:"林俊杰"},{key:"C",text:"方文山"},{key:"D",text:"易家扬"}],answer:"A",explanation:"《最向往的地方》由杨彤作词。"},
{id:"056",category:"歌曲",question:"《离开的那一些》作词人是？",options:[{key:"A",text:"方文山"},{key:"B",text:"林俊杰"},{key:"C",text:"小寒"},{key:"D",text:"葛大为"}],answer:"A",explanation:"《离开的那一些》由方文山作词。"},
{id:"058",category:"歌曲",question:"《愿与愁》作词人是？",options:[{key:"A",text:"方文山"},{key:"B",text:"易家扬"},{key:"C",text:"小寒"},{key:"D",text:"林怡凤"}],answer:"C",explanation:"《愿与愁》由小寒作词，是专辑的主打歌曲。"},
{id:"059",category:"歌曲",question:"《孤独娱乐》作词人是？",options:[{key:"A",text:"易家扬"},{key:"B",text:"方文山"},{key:"C",text:"小寒"},{key:"D",text:"林雨果"}],answer:"A",explanation:"《孤独娱乐》由易家扬作词。"},
{id:"060",category:"歌曲",question:"《自画像》作词人是？",options:[{key:"A",text:"林俊杰"},{key:"B",text:"林怡凤"},{key:"C",text:"方文山"},{key:"D",text:"小寒"}],answer:"B",explanation:"《自画像》由林怡凤作词。"},
// ===== 个人信息 - 8题 =====
{id:"061",category:"个人信息",question:"林俊杰的本名（非艺名）是什么？",options:[{key:"A",text:"JJ Lin"},{key:"B",text:"Wayne"},{key:"C",text:"Lim Junjie"},{key:"D",text:"林俊峰"}],answer:"B",explanation:"林俊杰本名Wayne，JJ Lin为艺名，Lim Junjie为外文名拼音。"},
{id:"062",category:"个人信息",question:"林俊杰的出生日期是？",options:[{key:"A",text:"1981年3月27日"},{key:"B",text:"1982年3月27日"},{key:"C",text:"1981年5月27日"},{key:"D",text:"1980年3月27日"}],answer:"A",explanation:"林俊杰于1981年3月27日出生于新加坡。"},
{id:"063",category:"个人信息",question:"林俊杰的祖籍是哪里？",options:[{key:"A",text:"中国福建省福州市"},{key:"B",text:"中国福建省泉州市"},{key:"C",text:"中国福建省厦门市"},{key:"D",text:"中国广东省潮州市"}],answer:"C",explanation:"林俊杰祖籍中国福建省厦门市同安区。"},
{id:"064",category:"个人信息",question:"林俊杰的星座和血型分别是？",options:[{key:"A",text:"双鱼座、A型"},{key:"B",text:"白羊座、O型"},{key:"C",text:"金牛座、B型"},{key:"D",text:"白羊座、AB型"}],answer:"B",explanation:"林俊杰星座为白羊座，血型为O型。"},
{id:"065",category:"个人信息",question:"林俊杰的应援色是？",options:[{key:"A",text:"蓝色"},{key:"B",text:"红色"},{key:"C",text:"紫色"},{key:"D",text:"绿色"}],answer:"C",explanation:"林俊杰的应援色为紫色。"},
{id:"066",category:"个人信息",question:"林俊杰于哪一年成立了个人音乐制作公司JFJ Productions？",options:[{key:"A",text:"2005年"},{key:"B",text:"2006年"},{key:"C",text:"2007年"},{key:"D",text:"2008年"}],answer:"C",explanation:"林俊杰于2007年3月27日成立了JFJ Productions，正式自立门户。"},
{id:"067",category:"个人信息",question:"林俊杰的哥哥林俊峰的职业是？",options:[{key:"A",text:"新加坡电信公司董事"},{key:"B",text:"瑞士银行亚太区副总裁"},{key:"C",text:"佳能公司CEO"},{key:"D",text:"石油公司负责人"}],answer:"B",explanation:"林俊杰的哥哥林俊峰是瑞士银行亚太区副总裁。"},
{id:"068",category:"个人信息",question:"林俊杰于哪一年考取了国际汽车联盟（FIA）的职业赛车驾照？",options:[{key:"A",text:"2014年"},{key:"B",text:"2015年"},{key:"C",text:"2016年"},{key:"D",text:"2017年"}],answer:"C",explanation:"林俊杰于2016年6月顺利考取FIA职业证照，成为职业赛车手。"},
// ===== 获奖记录 - 10题 =====
{id:"069",category:"获奖记录",question:"林俊杰凭借首张专辑《乐行者》获得了第几届台湾金曲奖的最佳新人奖？",options:[{key:"A",text:"第13届"},{key:"B",text:"第14届"},{key:"C",text:"第15届"},{key:"D",text:"第16届"}],answer:"C",explanation:"林俊杰凭借《乐行者》获得第15届台湾金曲奖最佳新人奖。"},
{id:"070",category:"获奖记录",question:"林俊杰首次获得台湾金曲奖最佳国语男歌手奖是凭借哪张专辑？",options:[{key:"A",text:"《她说》"},{key:"B",text:"《学不会》"},{key:"C",text:"《因你而在》"},{key:"D",text:"《新地球》"}],answer:"C",explanation:"林俊杰凭借《因你而在》获得第25届台湾金曲奖最佳国语男歌手奖。"},
{id:"071",category:"获奖记录",question:"林俊杰第二次获得台湾金曲奖最佳国语男歌手奖是凭借哪张专辑？",options:[{key:"A",text:"《新地球》"},{key:"B",text:"《和自己对话》"},{key:"C",text:"《伟大的渺小》"},{key:"D",text:"《学不会》"}],answer:"B",explanation:"林俊杰凭借《和自己对话》获得第27届台湾金曲奖最佳国语男歌手奖。"},
{id:"072",category:"获奖记录",question:"截至目前，林俊杰共计获得过几座台湾金曲奖？",options:[{key:"A",text:"2座"},{key:"B",text:"3座"},{key:"C",text:"4座"},{key:"D",text:"5座"}],answer:"C",explanation:"林俊杰自出道以来共计获得过4座台湾金曲奖。"},
{id:"073",category:"获奖记录",question:"林俊杰凭借哪首为他人创作的歌曲入围了第26届台湾金曲奖最佳作曲人奖？",options:[{key:"A",text:"《记得》"},{key:"B",text:"《一眼万年》"},{key:"C",text:"《你给我听好》"},{key:"D",text:"《身后》"}],answer:"C",explanation:"林俊杰凭借为陈奕迅创作的《你给我听好》入围第26届金曲奖最佳作曲人奖和最佳单曲制作人奖。"},
{id:"074",category:"获奖记录",question:"林俊杰凭借专辑《100天》入围了第几届台湾金曲奖最佳国语男歌手奖？",options:[{key:"A",text:"第20届"},{key:"B",text:"第21届"},{key:"C",text:"第22届"},{key:"D",text:"第23届"}],answer:"B",explanation:"林俊杰凭借《100天》入围第21届台湾金曲奖最佳国语男歌手奖。"},
{id:"075",category:"获奖记录",question:"林俊杰凭借《伟大的渺小》入围了第29届台湾金曲奖多个奖项，以下哪个不是入围奖项？",options:[{key:"A",text:"最佳国语男歌手奖"},{key:"B",text:"最佳国语专辑奖"},{key:"C",text:"最佳年度歌曲奖"},{key:"D",text:"最佳新人奖"}],answer:"D",explanation:"第29届金曲奖林俊杰入围了最佳国语男歌手奖、最佳国语专辑奖、最佳年度专辑奖、最佳专辑制作人奖、最佳年度歌曲奖、最佳作曲人奖，未入围最佳新人奖。"},
{id:"076",category:"获奖记录",question:"林俊杰凭借专辑《重拾_快乐》和歌曲《愿与愁》入围了第35届台湾金曲奖哪两个奖项？",options:[{key:"A",text:"最佳华语男歌手奖、最佳作曲人奖"},{key:"B",text:"最佳华语专辑奖、最佳作词人奖"},{key:"C",text:"最佳年度歌曲奖、最佳作曲人奖"},{key:"D",text:"最佳华语男歌手奖、最佳专辑制作人奖"}],answer:"A",explanation:"林俊杰凭借《重拾_快乐》入围最佳华语男歌手奖，凭借《愿与愁》入围最佳作曲人奖。"},
{id:"077",category:"获奖记录",question:"林俊杰在第21届台湾金曲奖颁奖典礼上的表演被媒体称为什么？",options:[{key:"A",text:"金曲之王"},{key:"B",text:"无冕之王"},{key:"C",text:"最佳表演"},{key:"D",text:"华语之光"}],answer:"B",explanation:"中国内地媒体将林俊杰称为当届金曲奖的无冕之王，台湾媒体则认为他拯救了金曲奖。"},
{id:"078",category:"获奖记录",question:"林俊杰曾受邀担任第26届台湾金曲奖的什么角色？",options:[{key:"A",text:"评审"},{key:"B",text:"主持人"},{key:"C",text:"官方宣传大使"},{key:"D",text:"开场表演嘉宾"}],answer:"C",explanation:"2015年5月，林俊杰受邀担任第26届台湾金曲奖颁奖典礼的官方宣传大使。"}
];

App.DEFAULT_QUESTION_BANK = JSON.parse(JSON.stringify(App.QUESTION_BANK));
